### ISSUE TITLE
你好，请问数据源从哪里获得？同时有无英语二的数据源？

### ISSUE THREAD

**Issue by mingcheng** [awxiaoxian2020/NETEMVocabulary#1]
如题，其实是两个问题，有多打扰

**Comment by awxiaoxian2020** [comment]
数据源就是这个 [json 文件](https://github.com/awxiaoxian2020/NETEMVocabulary/blob/master/vocabulary.json)
如果你指的是文本来源，那就是历年英语一和英语二的试题。
如果你指的是词汇表来源，那就是2023年的考纲词汇表，由人工逐一录入。
英语一和二的词汇表应该是一样的。

如果你指的是只对英语二进行统计，个人认为样本量太小，不具统计意义。
另外[词汇表](https://github.com/awxiaoxian2020/NETEMVocabulary/releases/download/v1.0.0/5530.beta._publish.pdf)**初版**已发布在 [Release](https://github.com/awxiaoxian2020/NETEMVocabulary/releases) .

**Comment by awxiaoxian2020** [comment]
如果您愿意为词频统计做出一些其他贡献的话，欢迎说明意图。
由于 office 文件并不能被 Git 跟踪，所以目前没有打算直接公开上传考纲词汇表的打算。
